config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :images
  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :image

  def self.sentiment_response(content)
    query = {"text" => "#{content}"}
    headers = {
      "X-Mashape-Key" => "#{ENV["SENTIMENT_KEY"]}",
      "Accept" => "application/json"
    }

    response = HTTParty.post(
      "https://twinword-sentiment-analysis.p.mashape.com/analyze/",
      :query => query,
      :headers => headers
    )

    mood = response["type"]
  end
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :entries

  def self.unsplash_response(keyword)
    response = HTTParty.get("https://api.unsplash.com/search/photos?client_id=#{ENV["UNSPLASH_KEY"]}&query=#{keyword}")
    return JSON.parse(response.body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new
    @entry.content = params[:entry][:content]
    @entry.mood = Entry.sentiment_response(@entry.content)
    @entry.image = Image.where(mood: @entry.mood).sample

    if @entry.save
      redirect_to root_url
    else
      render :new
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    # @image = randomImage(Image.unsplash_response("computer, coffee, pens"))
    @image = Image.new
  end

  def create
    @image = Image.new
    @image.image_url = randomImage(Image.unsplash_response("computer, coffee, pens"))

    # if @entry.mood == "positive"
      @image.mood = "positive"
    # end

    if @image.save
      redirect_to root_url
    else
      render :index
    end
  end

  def randomImage(response)
    response["results"].sample["urls"]["regular"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/entries/index.html.erb
<h1>Entries</h1>
<%= link_to 'New', new_entry_path %>
<%= link_to 'Images', images_path %><br><br>

<% @entries.each do |entry| %>
  <p>
    <%= entry.content %><br>
    <%= entry.mood %><br>
    <%= image_tag(entry.image.image_url) %>
  </p>
<% end %>

app/views/entries/new.html.erb
<%= form_for @entry, html: {class: 'form'} do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, placeholder: "Write an entry here" %>
  </div>

  <div class="field">
    <%= f.submit class: 'btn-default' %>
  </div>
<% end %>

app/views/images/index.html.erb
<h1>Unsplash Test</h1>
<%= link_to 'New Image', new_image_path %>
<%= link_to 'Entries', entries_path %><br><br>

<%= image_tag(@image) %>

<%= form_for @image, html: {class: 'form'} do |f| %>
  <div class="field">
    <%= f.submit class: 'btn-default' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnsplashTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>